blog/urls.py
from django.conf.urls import url

from . import views

app_name = "blog"
urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/like/$', views.PostLikeView.as_view(), name="like"),
]

exmaster/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import expenses.views

urlpatterns = [
    url(r'', include('expenses.urls')),
    url(r'blog/', include('blog.urls')),
    url(r'^login/$', expenses.views.LoginView.as_view(), name='login'),
    url(r'^logout/$', expenses.views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses/urls.py
from django.conf.urls import url

from . import views

app_name = "expenses"
urlpatterns = [
    url(r'^$', views.ListExpensesView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.ExpenseDetailView.as_view(), name="detail"),
    url(r'^add-account/$', views.CreateAccountView.as_view(),
        name="create_account"),
    url(r'^add-expense/$', views.CreateExpenseView.as_view(), name="create"),
]

expenses/models.py
from django.conf import settings
from django.core.urlresolvers import reverse

from django.db import models


class Account(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='accounts')
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


class Expense(models.Model):
    account = models.ForeignKey(Account, related_name='expenses', verbose_name=_("account"))
    date = models.DateField(_("date"), db_index=True)
    amount = models.DecimalField(_("amount"), max_digits=12, decimal_places=2)
    title = models.CharField(_("title"), max_length=200)
    description = models.TextField(_("description"), null=True, blank=True)
    # TODO: add security
    photo = models.ImageField(_("photo"), upload_to="expenses/", null=True, blank=True)

    def __str__(self):
        return "[#{}] ${}@{} ({})".format(
            self.pk or "?",
            self.amount,
            self.date,
            self.title,
        )

    def get_absolute_url(self):
        return reverse("expenses:detail", args=(self.pk,))

expenses/forms.py
from django import forms

from . import models


class LoginForm(forms.Form):
    username = forms.CharField(max_length=300)
    password = forms.CharField(max_length=300, widget=forms.PasswordInput())


class AccountForm(forms.ModelForm):
    class Meta:
        model = models.Account
        exclude = (
            'user',
        )


# class ExpenseForm(forms.ModelForm):
#     class Meta:
#         model = models.Expense
#         exclude = (
#         )

expenses/views.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy, reverse
from django.db.models import Sum
from django.http import HttpResponse
from django.shortcuts import redirect
from django.utils.encoding import escape_uri_path
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView

from . import forms
from . import models


class DummyView(View):
    def get(self, request):
        from django.core.mail import send_mail

        send_mail(
            'Subject here',
            'Here is the message.',
            'from@example.com',
            ['to@example.com'],
        )
        request.session['n'] = request.session.get('n', 0) + 1
        return HttpResponse("n = {}".format(request.session['n']))


class DummyView2(View):
    def get(self, request):
        assert False, request.session['visits']


class LoginView(FormView):
    form_class = forms.LoginForm
    template_name = "login.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('expenses:list')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

        if user is not None and user.is_active:
            login(self.request, user)
            if self.request.GET.get('from'):
                return redirect(
                    self.request.GET['from'])  # SECURITY: check path
            return redirect('expenses:list')

        form.add_error(None, _("Invalid user name or password"))
        return self.form_invalid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")


class LoggedInMixin:
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            url = reverse("login") + "?from=" + escape_uri_path(request.path)
            return redirect(url)
        return super().dispatch(request, *args, **kwargs)


class ListExpensesView(LoggedInMixin, ListView):
    model = models.Expense
    paginate_by = 10
    page_title = _("Home")

    def get_queryset(self):
        return super().get_queryset().filter(account__user=self.request.user)

    def total(self):
        return self.get_queryset().aggregate(sum=Sum('amount'))['sum']


class ExpenseDetailView(LoggedInMixin, DetailView):
    model = models.Expense

    def get_queryset(self):
        return super().get_queryset().filter(account__user=self.request.user)

    def page_title(self):
        return self.object.title

        # def get_context_data(self, **kwargs):
        #     d = super().get_context_data(**kwargs)
        #     d['title123'] = self.object.title
        #     return d


class CreateAccountView(LoggedInMixin, CreateView):
    page_title = _("Add New Account")
    model = models.Expense
    form_class = forms.AccountForm

    success_url = reverse_lazy('expenses:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        resp = super().form_valid(form)
        messages.success(self.request, _("Account created successfully."))
        return resp


class CreateExpenseView(LoggedInMixin, CreateView):
    page_title = _("Add New Expense")
    model = models.Expense
    fields = (
        'account',
        'date',
        'amount',
        'title',
        'description',
        'photo',
    )

    # success_url = reverse_lazy('expenses:list')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        # form.fields['account'].queryset = models.Account.objects.filter(
        #     user=self.request.user)
        form.fields['account'].queryset = form.fields[
            'account'].queryset.filter(user=self.request.user)
        return form

    def get_initial(self):
        d = super().get_initial()
        d['date'] = datetime.date.today()
        return d

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

expenses/templates/base.html
{% load i18n staticfiles bootstrap3 %}
{% get_current_language_bidi as BIDI %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            {{ view.page_title }} | {% trans "ExMaster" %}
        {% endblock %}
    </title>
    {% if BIDI %}
        <link href="{% static "bootstrap/css/bootstrap-rtl.css" %}"
              rel="stylesheet">
    {% else %}
        <link href="{% static "bootstrap/css/bootstrap.css" %}"
              rel="stylesheet">
    {% endif %}
</head>
<body{% if BIDI %} dir="rtl"{% endif %}>

<div class="container">

    <div class="pull-right">
        <a href="{% url "blog:list" %}">Blog</a>
        |
        <a href="{% url "expenses:create_account" %}">Add Account</a>
        |
        <a href="{% url "expenses:create" %}">Add Expense</a>
        |
        {{ user }}
        |
        <a href="{% url 'logout' %}">Logout</a>
    </div>

    <h1>
        ExMaster!!!!!!!!!!!!!
    </h1>

    {% bootstrap_messages %}

    <div>

        {% block content %}
            CONTENT
        {% endblock %}

    </div>

</div>

<script src="{% static "jquery.js" %}"></script>
{% block scripts %}
{% endblock %}

</body>
</html>

expenses/templates/login.html
{% extends "base.html" %}
{% load i18n staticfiles bootstrap3%}
{% block content %}
<body>
    <div class="container">
    <h1>{{ page_title }}</h1>

        <form method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% trans "Login" %}
                    </button>
                {% endbuttons %}
        </form>
    </div>
</body>
{% endblock %}