blog/urls.py
from django.conf.urls import url

from . import views

app_name = "blog"
urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name="list"),
    url(r'^(?P<pk>\d+)/$', views.PostDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/like/$', views.PostLikeView.as_view(), name="like"),
]

exmaster/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import expenses.views

urlpatterns = [
    url(r'', include('expenses.urls')),
    url(r'blog/', include('blog.urls')),
    url(r'^login/$', expenses.views.LoginView.as_view(), name='login'),
    url(r'^logout/$', expenses.views.LogoutView.as_view(), name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import markdown
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=300)
    content = models.TextField()
    content_html = models.TextField(editable=False)

    def __str__(self):
        return self.title

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        self.content_html = markdown.markdown(self.content)
        super().save(force_insert, force_update, using, update_fields)

    def get_absolute_url(self):
        return reverse("blog:detail", args=(self.pk,))


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=300)
    content = models.TextField()

    def __str__(self):
        return self.title

        # def get_absolute_url(self):
        #     return reverse("blog:detail", args=(self.pk,))


class Like(models.Model):
    post = models.ForeignKey(Post, related_name="likes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="likes")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (
            ('post', 'user'),
        )

blog/forms.py
from django import forms

from . import models


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = (
            'title',
            'content',
        )

blog/views.py
import json

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.base import View
from django.views.generic.list import ListView

from blog import forms
from expenses.views import LoggedInMixin
from . import models


class PostListView(ListView):
    model = models.Post


class PostDetailView(LoggedInMixin, DetailView):
    model = models.Post

    def get_context_data(self, **kwargs):
        d = super().get_context_data(**kwargs)
        d['form'] = forms.CommentForm()
        return d

    def post(self, request, *args, **kwargs):
        parent = self.get_object()

        if request.POST.get('like'):
            # ADD/REMOVE LIKE
            assert False, "LIKE"
        else:
            # ADD COMMENT
            form = forms.CommentForm(request.POST)
            if not form.is_valid():
                return JsonResponse({
                    'errors': json.loads(form.errors.as_json()),
                }, status=400)
            form.instance.post = parent
            form.instance.user = request.user
            form.save()
            if request.is_ajax():
                # return JsonResponse({'status': 'ok'})
                return render(request, "blog/_comment.html", {
                    'comment': form.instance,
                })
            messages.success(request, "Comments saved.")
            return redirect(parent)


class PostLikeView(LoggedInMixin, View):
    def post(self, request, *args, **kwargs):
        parent = get_object_or_404(models.Post, id=kwargs['pk'])
        # parent = models.Post.objects.get(id=kwargs['pk'])
        # ADD/REMOVE LIKE
        assert False, "LIKE"

# class MyView(View):
#     def get(self, request, *args, **kwargs):
#
#         return JsonResponse({'data': [
#             {'x':123, 'y': i} for i in range(100, 1000, 20)]})

blog/templates/blog/_comment.html
{% load humanize %}


<li class="list-group-item">
    <p>
        <b>
            {{ comment.title }} ({{ comment.user }})
        </b>
        <i title="{{ comment.created_at }}">{{ comment.created_at|naturaltime }}</i>
    </p>
    {{ comment.content|linebreaks }}
</li>

blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load bootstrap3 staticfiles %}

{% block content %}

    <h1>{{ object }}</h1>

    {{ object.content_html|safe }}

    <p>

{#    <form method="post" id="likeform">#}
    <form method="post" id="likeform" action="{% url "blog:like" object.id %}">
        {% csrf_token %}
        <input type="hidden" name="like" value="1">
        <button class="btn btn-primary" id="send"><i
                class="glyphicon glyphicon-heart"></i> Like
        </button>
    </form>
    </p>



    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Add comment</h3>
        </div>
        <div class="panel-body">
            <form method="post" id="commentform">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary" id="send">Comment</button>
            </form>
        </div>
    </div>
    <ul class="list-group" id="comments">
        {% for comment in object.comments.all %}
            {% include "blog/_comment.html" %}
        {% endfor %}
    </ul>


{% endblock %}

{% block scripts %}
    <script src="{% static "csrf.js" %}"></script>
    <script src="{% static "post_detail.js" %}"></script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base.html" %}

{% block content %}
    <ul class="list-group">
        {% for object in object_list %}
            <li class="list-group-item">
                <a href="{{ object.get_absolute_url }}">
                    {{ object }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}